function script = appendPickToBinToScript(script, pickData, binParams, motionParams)
%APPENDPICKTOBINTOSCRIPT Append URScript for picking a piece and dropping it to bin.
%
%   script = appendPickToBinToScript(script, pickData, binParams, motionParams)
%
%   pickData is generated by generatePickToBinData().
%   binParams is generated by robotBinParams().
%   motionParams is generated by robotMotionParams().
%
%   Convention:
%   - pickData poses are already converted to meters by generatePickToBinData().
%   - binParams.P_BIN_DROP has XYZ in mm and rotation in rad, so this function
%     converts only XYZ to meters before appending movel.

    arguments
        script string
        pickData struct
        binParams struct
        motionParams struct
    end

    a_joint = motionParams.a_joint;
    v_joint = motionParams.v_joint;
    a_lin = motionParams.a_lin;
    v_lin = motionParams.v_lin;

    %% Move to piece region high
    script = script + "  # PICK TO BIN - go to piece region" + newline;
    script = appendMoveJ(script, pickData.Q_HIGH, a_joint, v_joint);

    %% Pick sequence
    script = script + "  # PICK TO BIN - pick piece" + newline;

    script = appendMoveL(script, pickData.P_APPROACH_HIGH, a_lin, v_lin);

    if isfield(pickData, "P_APPROACH_MID") && ~isempty(pickData.P_APPROACH_MID)
        script = appendMoveL(script, pickData.P_APPROACH_MID, a_lin, v_lin);
    end

    script = appendMoveL(script, pickData.P_APPROACH_LOW,  a_lin, v_lin);
    script = appendMoveL(script, pickData.P_INSERT_FLAT,   a_lin, v_lin);
    script = appendMoveL(script, pickData.P_ROTATE_LOCK,   a_lin, v_lin);
    script = appendMoveL(script, pickData.P_LIFT_LOCKED,   a_lin, v_lin);
    script = appendMoveL(script, pickData.P_EXIT_HIGH,     a_lin, v_lin);

    %% Return to piece region high
    script = script + "  # PICK TO BIN - return to piece region high" + newline;
    script = appendMoveJ(script, pickData.Q_HIGH, a_joint, v_joint);

    %% Move to bin high
    script = script + "  # PICK TO BIN - go to bin" + newline;
    script = appendMoveJ(script, binParams.Q_BIN_HIGH, a_joint, v_joint);

    %% Bin drop
    pDrop = binParams.P_BIN_DROP;
    pDrop(1:3) = pDrop(1:3) / 1000;

    script = script + "  # PICK TO BIN - drop piece" + newline;
    script = appendMoveL(script, pDrop, a_lin, v_lin);
    script = script + "  sleep(0.3)" + newline;

    %% Back to bin high
    script = script + "  # PICK TO BIN - back to bin high" + newline;
    script = appendMoveJ(script, binParams.Q_BIN_HIGH, a_joint, v_joint);
end
