function script = appendQueenPickToScript(script, queenPickData, motionParams)
%APPENDQUEENPICKTOSCRIPT Append URScript sequence for picking queen from storage.
%
%   queenPickData should be generated by generateQueenPickData(queenParams).
%   motionParams should be generated by robotMotionParams().
%
%   Sequence:
%   Q_QUEEN_HIGH
%   APPROACH_HIGH
%   APPROACH_MID, if defined
%   APPROACH_LOW
%   INSERT_FLAT
%   ROTATE_LOCK
%   LIFT_LOCKED
%   EXIT_HIGH
%   Q_QUEEN_HIGH

    arguments
        script string
        queenPickData struct
        motionParams struct
    end

    %% Move to queen storage high

    script = appendMoveJ(script, queenPickData.Q_HIGH, ...
        motionParams.a_joint, motionParams.v_joint);

    %% Pick queen from storage

    script = appendMoveL(script, queenPickData.P_APPROACH_HIGH, ...
        motionParams.a_lin, motionParams.v_lin);

    if isfield(queenPickData, "P_APPROACH_MID") && ~isempty(queenPickData.P_APPROACH_MID)
        script = appendMoveL(script, queenPickData.P_APPROACH_MID, ...
            motionParams.a_lin, motionParams.v_lin);
    end

    script = appendMoveL(script, queenPickData.P_APPROACH_LOW, ...
        motionParams.a_lin, motionParams.v_lin);

    script = appendMoveL(script, queenPickData.P_INSERT_FLAT, ...
        motionParams.a_lin, motionParams.v_lin);

    script = appendMoveL(script, queenPickData.P_ROTATE_LOCK, ...
        motionParams.a_lin, motionParams.v_lin);

    script = appendMoveL(script, queenPickData.P_LIFT_LOCKED, ...
        motionParams.a_lin, motionParams.v_lin);

    script = appendMoveL(script, queenPickData.P_EXIT_HIGH, ...
        motionParams.a_lin, motionParams.v_lin);

    %% Return to queen storage high

    script = appendMoveJ(script, queenPickData.Q_HIGH, ...
        motionParams.a_joint, motionParams.v_joint);
end
